import type { Metadata } from "next";
import {Dosis} from 'next/font/google'
import "./globals.css";
import Header from "./Components/UI/Header/Header";

const dosis = Dosis({
  subsets: ['latin'],
  weight: ['400', '700']
})


export const metadata: Metadata = {
  title: "Qitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
